<a href="https://colab.research.google.com/github/M-chandrika27/Real-time-E-commerece-order-processing-Weather-and-Sales-data-analysis./blob/main/project_on_slaes_data%2C_weather_and_and_E_commerce_order_processing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Project**

**1.Real-time E-commerece-order-processing.**

##sample data

In [ ]:
product1_name='Laptop'
product1_price=1000
product1_stock=5
product2_name='Phone'
product2_price=500
product2_stock=10
product3_name='HeadPhones'
product3_price=100
product3_stock=50
order1_product='Laptop'
order1_quantity=1
order2_product='Phone'
order2_quantity=2
order3_product='HeadPhones'
order3_quantity=3
customer_name='John Doe'
customer_loyalty_points=150
customer_is_member=True

#constants and initalize variables

In [ ]:
#constants
DISCOUNT_RATE=0.1
POINTS_RATE=0.01
MINIMUM_POINTS_FOR_DISCOUNT=100
#initialize variables
total_price=0

#order processing

In [ ]:
#process order1
if order1_product==product1_name and product1_stock>=order1_quantity:
  order1_price=product1_price*order1_quantity
  if customer_is_member:
    order1_price-=order1_price*DISCOUNT_RATE
  total_price+=order1_price
  product1_stock-=order1_quantity
else:
  print(f"sorry,we can't fulfull the order for{order1_product}.Not enough stock or product does not exist.")
#process order2
if order2_product==product2_name and product2_stock>=order2_quantity:
  order2_price=product2_price*order2_quantity
  if customer_is_member:
    order2_price-=order2_price*DISCOUNT_RATE
  total_price+=order2_price
  product2_stock-=order2_quantity
else:
  print(f"sorry,we can't fulfull the order for{order2_product}.Not enough stock or product does not exist.")
#process order3
if order3_product==product3_name and product3_stock>=order3_quantity:
  order3_price=product3_price*order3_quantity
  if customer_is_member:
    order3_price-=order3_price*DISCOUNT_RATE
  total_price+=order3_price
  product3_stock-=order3_quantity
else:
  print(f"sorry,we can't fulfull the order for{order3_product}.Not enough stock or product does not exist.")

#calculating loyalty points earned

In [ ]:
#calculating loyalty points earned
Loyalty_points_earned=int(total_price*POINTS_RATE)
customer_loyalty_points+=Loyalty_points_earned

#Apply additional discount if customer has enough loyality points

In [ ]:
if customer_loyalty_points>=MINIMUM_POINTS_FOR_DISCOUNT:
  total_price-=total_price*DISCOUNT_RATE
print("Additional discount applied due to loyalty points.")

Additional discount applied due to loyalty points.


#summary

In [ ]:
#summary
print(f"order processed for:{customer_name}")
print(f"Total price:${total_price:.2f}")
print(f"loyalty points earned:{Loyalty_points_earned}")
print(f"Total loyalty points:{customer_loyalty_points}")
print(f"updated product stock:{product1_name}={product1_stock},{product2_name}={product2_stock},{product3_name}={product3_stock}")

order processed for:John Doe
Total price:$1863.00
loyalty points earned:20
Total loyalty points:170
updated product stock:Laptop=4,Phone=8,HeadPhones=47


summary:

This Python-driven real-time e-commerce system processes orders instantly, as seen with John Doe's $1863.00 purchase. It simultaneously updates stock (e.g., Laptop to 4, Phone to 8), calculates new loyalty points, and applies discounts, streamlining fulfillment and inventory management.

**2.Weather data Analysis**

**Real-Life Implementation Scenario :-** weather data analysis.

**Scenario description:-**we are going to analyze weather data using numpy.we will perform various operations such as loading data, basic analysis, statistical operations and reshaping data.

#import libraries

In [ ]:
import numpy as np

#sample weather data:Temperature readings(i=Celsius)for a week

In [ ]:
import numpy as np
weather_data=np.array([[23,25,22,20,24,26,27],#monday
    [22,24,23,19,22,25,26],#tuesday
    [21,23,20,18,23,24,25],#wednessday
    [20,22,19,17,21,23,24],#thrusday
    [19,21,18,16,20,22,23],#friday
    [18,20,17,15,19,21,22],#satruday
    [17,19,16,14,18,20,21]])#sunday
print("weather data:\n",weather_data)

weather data:
 [[23 25 22 20 24 26 27]
 [22 24 23 19 22 25 26]
 [21 23 20 18 23 24 25]
 [20 22 19 17 21 23 24]
 [19 21 18 16 20 22 23]
 [18 20 17 15 19 21 22]
 [17 19 16 14 18 20 21]]


step-2:Basic analysis

In [ ]:
#average temperature for each day
average_temp_daily=np.mean(weather_data,axis=1)
print("average temperature for each day:\n",average_temp_daily)

average temperature for each day:
 [23.85714286 23.         22.         20.85714286 19.85714286 18.85714286
 17.85714286]


In [ ]:
#average temperature for each week
average_temp_weekly=np.mean(weather_data)
print("average temperature for each week:\n",average_temp_weekly)

average temperature for each week:
 20.897959183673468


step-3:statistical opreation

In [ ]:
#maximum temperature for each day
max_temp_daily=np.max(weather_data,axis=1)
print("maximum temperature for each day:\n",max_temp_daily)

maximum temperature for each day:
 [27 26 25 24 23 22 21]


In [ ]:
#manimum temperature for each day
min_temp_daily=np.min(weather_data,axis=1)
print("minimum temperature for each day:\n",min_temp_daily)

minimum temperature for each day:
 [20 19 18 17 16 15 14]


In [ ]:
#standard derivation of temperature for the week
std_temp_weekly=np.std(weather_data)
print("standard deviation of weekly temperature:",std_temp_weekly)

standard deviation of weekly temperature: 3.0118466635711454


step-4:reshaping data

In [ ]:
#flatten the data to perform element wise operations
weather_data_flattened=weather_data.flatten()
print("flattened weather data:\n",weather_data_flattened)

flattened weather data:
 [23 25 22 20 24 26 27 22 24 23 19 22 25 26 21 23 20 18 23 24 25 20 22 19
 17 21 23 24 19 21 18 16 20 22 23 18 20 17 15 19 21 22 17 19 16 14 18 20
 21]


In [ ]:
#reshaping the flattened data back to its orginal shape
weather_data_reshaped=weather_data_flattened.reshape(weather_data.shape)
print("reshaped weather data:\n",weather_data_reshaped)

reshaped weather data:
 [[23 25 22 20 24 26 27]
 [22 24 23 19 22 25 26]
 [21 23 20 18 23 24 25]
 [20 22 19 17 21 23 24]
 [19 21 18 16 20 22 23]
 [18 20 17 15 19 21 22]
 [17 19 16 14 18 20 21]]


Summary:-

NumPy allows efficient storage and manipulation of daily temperature readings for a week as an array. This enables quick calculations like the average, maximum, and minimum temperatures across those seven days using vectorized operations.

**3.Sales data analysis.**

**Real-life implementation scenarios:**Sales data analysis.

**import libraries**

In [ ]:
import pandas as pd

**load the data**

In [ ]:
#Load sales data
Sales_data={'Date':['2021-01-01','2021-01-02','2021-01-03','2021-01-04'],
            'store':['Store A','Store B','Store A','Store B'],
            'Sales':[200,150,220,None]}
Sales_data=pd.DataFrame(Sales_data)
Sales_data

Date    store  Sales
0  2021-01-01  Store A  200.0
1  2021-01-02  Store B  150.0
2  2021-01-03  Store A  220.0
3  2021-01-04  Store B    NaN

In [ ]:
#example problem for loading data in csv format
df=pd.read_csv("/survey.csv")
df

Timestamp  Age  Gender         Country state self_employed  \
0     2014-08-27 11:29:31   37  Female   United States    IL           NaN   
1     2014-08-27 11:29:37   44       M   United States    IN           NaN   
2     2014-08-27 11:29:44   32    Male          Canada   NaN           NaN   
3     2014-08-27 11:29:46   31    Male  United Kingdom   NaN           NaN   
4     2014-08-27 11:30:22   31    Male   United States    TX           NaN   
...                   ...  ...     ...             ...   ...           ...   
1254  2015-09-12 11:17:21   26    male  United Kingdom   NaN            No   
1255  2015-09-26 01:07:35   32    Male   United States    IL            No   
1256  2015-11-07 12:36:58   34    male   United States    CA            No   
1257  2015-11-30 21:25:06   46       f   United States    NC            No   
1258  2016-02-01 23:04:31   25    Male   United States    IL            No   

     family_history treatment work_interfere    no_employees  ...  \
0                No       Yes          Often            6-25  ...   
1                No        No         Rarely  More than 1000  ...   
2                No        No         Rarely            6-25  ...   
3               Yes       Yes          Often          26-100  ...   
4                No        No          Never         100-500  ...   
...             ...       ...            ...             ...  ...   
1254             No       Yes            NaN          26-100  ...   
1255            Yes       Yes          Often          26-100  ...   
1256            Yes       Yes      Sometimes  More than 1000  ...   
1257             No        No            NaN         100-500  ...   
1258            Yes       Yes      Sometimes          26-100  ...   

                   leave mental_health_consequence phys_health_consequence  \
0          Somewhat easy                        No                      No   
1             Don't know                     Maybe                      No   
2     Somewhat difficult                        No                      No   
3     Somewhat difficult                       Yes                     Yes   
4             Don't know                        No                      No   
...                  ...                       ...                     ...   
1254       Somewhat easy                        No                      No   
1255  Somewhat difficult                        No                      No   
1256  Somewhat difficult                       Yes                     Yes   
1257          Don't know                       Yes                      No   
1258          Don't know                     Maybe                      No   

         coworkers    supervisor mental_health_interview  \
0     Some of them           Yes                      No   
1               No            No                      No   
2              Yes           Yes                     Yes   
3     Some of them            No                   Maybe   
4     Some of them           Yes                     Yes   
...            ...           ...                     ...   
1254  Some of them  Some of them                      No   
1255  Some of them           Yes                      No   
1256            No            No                      No   
1257            No            No                      No   
1258  Some of them            No                      No   

     phys_health_interview mental_vs_physical obs_consequence comments  
0                    Maybe                Yes              No      NaN  
1                       No         Don't know              No      NaN  
2                      Yes                 No              No      NaN  
3                    Maybe                 No             Yes      NaN  
4                      Yes         Don't know              No      NaN  
...                    ...                ...             ...      ...  
1254                    No         Don't know              No      NaN  
1255    

In [ ]:
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [ ]:
df_new=df
columns_to_fill = ["work_interfere", "self_employed", "state"]
df_new[columns_to_fill] = df_new[columns_to_fill].fillna(method='bfill')
df_new

/tmp/ipython-input-26-486171357.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_new[columns_to_fill] = df_new[columns_to_fill].fillna(method='bfill')


Timestamp  Age  Gender         Country state self_employed  \
0     2014-08-27 11:29:31   37  Female   United States    IL           Yes   
1     2014-08-27 11:29:37   44       M   United States    IN           Yes   
2     2014-08-27 11:29:44   32    Male          Canada    TX           Yes   
3     2014-08-27 11:29:46   31    Male  United Kingdom    TX           Yes   
4     2014-08-27 11:30:22   31    Male   United States    TX           Yes   
...                   ...  ...     ...             ...   ...           ...   
1254  2015-09-12 11:17:21   26    male  United Kingdom    IL            No   
1255  2015-09-26 01:07:35   32    Male   United States    IL            No   
1256  2015-11-07 12:36:58   34    male   United States    CA            No   
1257  2015-11-30 21:25:06   46       f   United States    NC            No   
1258  2016-02-01 23:04:31   25    Male   United States    IL            No   

     family_history treatment work_interfere    no_employees  ...  \
0                No       Yes          Often            6-25  ...   
1                No        No         Rarely  More than 1000  ...   
2                No        No         Rarely            6-25  ...   
3               Yes       Yes          Often          26-100  ...   
4                No        No          Never         100-500  ...   
...             ...       ...            ...             ...  ...   
1254             No       Yes          Often          26-100  ...   
1255            Yes       Yes          Often          26-100  ...   
1256            Yes       Yes      Sometimes  More than 1000  ...   
1257             No        No      Sometimes         100-500  ...   
1258            Yes       Yes      Sometimes          26-100  ...   

                   leave mental_health_consequence phys_health_consequence  \
0          Somewhat easy                        No                      No   
1             Don't know                     Maybe                      No   
2     Somewhat difficult                        No                      No   
3     Somewhat difficult                       Yes                     Yes   
4             Don't know                        No                      No   
...                  ...                       ...                     ...   
1254       Somewhat easy                        No                      No   
1255  Somewhat difficult                        No                      No   
1256  Somewhat difficult                       Yes                     Yes   
1257          Don't know                       Yes                      No   
1258          Don't know                     Maybe                      No   

         coworkers    supervisor mental_health_interview  \
0     Some of them           Yes                      No   
1               No            No                      No   
2              Yes           Yes                     Yes   
3     Some of them            No                   Maybe   
4     Some of them           Yes                     Yes   
...            ...           ...                     ...   
1254  Some of them  Some of them                      No   
1255  Some of them           Yes                      No   
1256            No            No                      No   
1257            No            No                      No   
1258  Some of them            No                      No   

     phys_health_interview mental_vs_physical obs_consequence comments  
0                    Maybe                Yes              No      NaN  
1                       No         Don't know              No      NaN  
2                      Yes                 No              No      NaN  
3                    Maybe                 No             Yes      NaN  
4                      Yes         Don't know              No      NaN  
...                    ...                ...             ...      ...  
1254                    No         Don't know              No      NaN  
1255    

In [ ]:
df_new.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                           0
self_employed                   0
family_history                  0
treatment                       0
work_interfere                  0
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

step-2:Handling Missing values

In [ ]:
#Filling missing sales with the mean Sales Value
Sales_data['Sales']=Sales_data['Sales'].fillna(Sales_data['Sales'].mean())
Sales_data

Date    store  Sales
0  2021-01-01  Store A  200.0
1  2021-01-02  Store B  150.0
2  2021-01-03  Store A  220.0
3  2021-01-04  Store B  190.0

In [ ]:
Sales_data.isnull().sum()

Date     0
store    0
Sales    0
dtype: int64

step-3:-Merge Additional Data

In [ ]:
#Additional data:store locations
location_data={'store':['Store A','Store B'],'Location':['New York','Los Angeles']}
location_df=pd.DataFrame(location_data)
location_df

store     Location
0  Store A     New York
1  Store B  Los Angeles

In [ ]:
#Merging sales data with location data
merged_df=pd.merge(Sales_data,location_df,on='store')
merged_df

Date    store  Sales     Location
0  2021-01-01  Store A  200.0     New York
1  2021-01-02  Store B  150.0  Los Angeles
2  2021-01-03  Store A  220.0     New York
3  2021-01-04  Store B  190.0  Los Angeles

step-4:-Group and Aggregate Data

In [ ]:
#Group by 'Location' and calculate total sales
grouped_sales=merged_df.groupby('store').sum()
grouped_sales

Date  Sales                Location
store                                                       
Store A  2021-01-012021-01-03  420.0        New YorkNew York
Store B  2021-01-022021-01-04  340.0  Los AngelesLos Angeles

In [ ]:
grouped_sales=merged_df.groupby('Location').sum()
grouped_sales

Date           store  Sales
Location                                                
Los Angeles  2021-01-022021-01-04  Store BStore B  340.0
New York     2021-01-012021-01-03  Store AStore A  420.0

step-5:- Reshape Data

pivot table:Total sales by Date and location

In [ ]:
pivot_table=merged_df.pivot_table(values='Sales',index='Date',columns='Location',aggfunc='sum')
pivot_table

Location    Los Angeles  New York
Date                             
2021-01-01          NaN     200.0
2021-01-02        150.0       NaN
2021-01-03          NaN     220.0
2021-01-04        190.0       NaN

In [ ]:
#melt the pivot tables back to long format
melted_Sales=pd.melt(pivot_table.reset_index(),id_vars='Date',value_vars=['New York','Los Angeles'],var_name='Location',value_name='Sales')
melted_Sales

Date     Location  Sales
0  2021-01-01     New York  200.0
1  2021-01-02     New York    NaN
2  2021-01-03     New York  220.0
3  2021-01-04     New York    NaN
4  2021-01-01  Los Angeles    NaN
5  2021-01-02  Los Angeles  150.0
6  2021-01-03  Los Angeles    NaN
7  2021-01-04  Los Angeles  190.0

Summary:-

"Pandas is crucial for sales data analysis, enabling tasks like cleaning missing sales records, combining data from different sales regions, and grouping sales figures by product or time. These operations allow for efficient analysis of sales performance and trends, forming a strong basis for further insights."